### ISSUE TITLE
Typo in the paper?

### ISSUE THREAD

**Issue by 3for** [algorand/pointproofs#15]
I'm reading [the paper ](https://eprint.iacr.org/2020/419.pdf)，I‘m not sure if the expression is right?
1）`m'` instead of  `m'[S]` ?
![image](https://user-images.githubusercontent.com/30716372/82673806-f80d9300-9c74-11ea-8d72-29888004589a.png)
2）`Commit` number is `nz(m)`, while `Prove` is `nz(m)-1`？
![image](https://user-images.githubusercontent.com/30716372/82674010-4458d300-9c75-11ea-9395-66d159306b74.png)

**Comment by reyzin** [comment]
Thank you for the corrections. You are right, and we'll update these in the next eprint update.

**Comment by 3for** [comment]
3）`2l` instead of `3l` ？
![image](https://user-images.githubusercontent.com/30716372/82775218-a7b35280-9e79-11ea-9e82-60afa101c0da.png)

**Comment by reyzin** [comment]
No, actually 3l -- for a rather subtle reason in the proof.

**Comment by reyzin** [comment]
Eprint updated https://eprint.iacr.org/2020/419. Thanks!
