### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by randoracle** [algorand/pointproofs#19]
Hi, thanks for the library!

I have some trouble building this library. Apparently, they are caused by the dependencies (`Pairing-plus` and/or `pointproofs-paramgen`).
After configuring `rand_core = "*"` and `rand_xorshift = "*"` (because if the version is left empty, there will be other errors), some errors like this come up:
```
error[E0599]: no function or associated item named `deserialize` found for struct `PointproofsParams` in the current scope
   --> src/pairings/param.rs:300:64
    |
300 |     let param = match pointproofs_paramgen::PointproofsParams::deserialize(reader, true) {
    |                                                                ^^^^^^^^^^^ function or associated item not found in `PointproofsParams`
    |
    = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
    |
4   | use pairing_plus::serdes::SerDes;
    |
```

Could you have a look? Thanks in advance!

**Comment by therainisme** [comment]
I had the same problem, did you solve it?

**Comment by randoracle** [comment]
> I had the same problem, did you solve it?

Yeah, try specifying the branch of the `pairing-plus` dependency in `Cargo.toml`. In other words, replace this line (line 20, `Cargo.toml`):
`pairing-plus = { git = "https://github.com/algorand/pairing-plus"}`
by the following line:
`pairing-plus = { git = "https://github.com/algorand/pairing-plus", branch="master"}`
